nav:
  - Home: index.md
  - Amphora:
      - createSecret:
          - createSecret_1000: reports/amphora/createSecret/createSecret_1000.md
          - createSecret_10000: reports/amphora/createSecret/createSecret_10000.md
          - createSecret_50000: reports/amphora/createSecret/createSecret_50000.md
          - createSecret_100000: reports/amphora/createSecret/createSecret_100000.md
          - createSecret_250000: reports/amphora/createSecret/createSecret_250000.md
          - createSecret_450000: reports/amphora/createSecret/createSecret_400000.md
      - getSecrets:
          - getSecrets_1000: reports/amphora/getSecrets/getSecrets_1000.md
          - getSecrets_11000: reports/amphora/getSecrets/getSecrets_11000.md
          - getSecrets_61000: reports/amphora/getSecrets/getSecrets_61000.md
          - getSecrets_161000: reports/amphora/getSecrets/getSecrets_161000.md
          - getSecrets_411000: reports/amphora/getSecrets/getSecrets_411000.md
          - getSecrets_861000: reports/amphora/getSecrets/getSecrets_861000.md
      - deleteSecret:
          - deleteSecret_861000: reports/amphora/deleteSecret/deleteSecret_811000.md

  - Castor:
      - createSecret:
          - createSecret_1000: reports/castor/createSecret/createSecret_1000.md
          - createSecret_10000: reports/castor/createSecret/createSecret_10000.md
          - createSecret_50000: reports/castor/createSecret/createSecret_50000.md
          - createSecret_100000: reports/castor/createSecret/createSecret_100000.md
          - createSecret_250000: reports/castor/createSecret/createSecret_250000.md
          - createSecret_450000: reports/castor/createSecret/createSecret_400000.md
      - getSecrets:
          - getSecrets_1000: reports/castor/getSecrets/getSecrets_1000.md
          - getSecrets_11000: reports/castor/getSecrets/getSecrets_11000.md
          - getSecrets_61000: reports/castor/getSecrets/getSecrets_61000.md
          - getSecrets_161000: reports/castor/getSecrets/getSecrets_161000.md
          - getSecrets_411000: reports/castor/getSecrets/getSecrets_411000.md
          - getSecrets_861000: reports/castor/getSecrets/getSecrets_861000.md
      - deleteSecret:
          - deleteSecret_861000: reports/castor/deleteSecret/deleteSecret_811000.md

  - Ephemeral:
      - emptyProgram:
          - 400000_concurrency_10: reports/ephemeral/epmtyProgram/400000_concurrency_10.md
      - scalarValueOptProgram:
          - 400000_concurrency_10: reports/ephemeral/scalarValueOptProgram/400000_concurrency_10.md
