nav:
  - Home: index.md
  - Amphora:
      - createSecret:
          - 1_000_secret_values: reports/amphora/createSecret_scenario/1_000_secret_values.md
          - 10_000_secret_values: reports/amphora/createSecret_scenario/10_000_secret_values.md
          - 50_000_secret_values: reports/amphora/createSecret_scenario/50_000_secret_values.md
          - 100_000_secret_values: reports/amphora/createSecret_scenario/100_000_secret_values.md
          - 250_000_secret_values: reports/amphora/createSecret_scenario/250_000_secret_values.md
          - 500_000_secret_values: reports/amphora/createSecret_scenario/500_000_secret_values.md
          - 750_000_secret_values: reports/amphora/createSecret_scenario/750_000_secret_values.md
      - getSecrets:
          - 1_000_secret_values: reports/amphora/getSecrets_scenario/1_000_secret_values.md
          - 11_000_secret_values: reports/amphora/getSecrets_scenario/11_000_secret_values.md
          - 61_000_secret_values: reports/amphora/getSecrets_scenario/61_000_secret_values.md
          - 161_000_secret_values: reports/amphora/getSecrets_scenario/161_000_secret_values.md
          - 411_000_secret_values: reports/amphora/getSecrets_scenario/411_000_secret_values.md
          - 911_000_secret_values: reports/amphora/getSecrets_scenario/911_000_secret_values.md
      - deleteSecret:
          - 1_661_000_secret_values: reports/amphora/deleteSecret_scenario/1_661_secret_values.md

  - Castor:
      - createSecret:
          - 1_000_secret_values: reports/castor/createSecret_scenario/1_000_secret_values.md
          - 10_000_secret_values: reports/castor/createSecret_scenario/10_000_secret_values.md
          - 50_000_secret_values: reports/castor/createSecret_scenario/50_000_secret_values.md
          - 100_000_secret_values: reports/castor/createSecret_scenario/100_000_secret_values.md
          - 250_000_secret_values: reports/castor/createSecret_scenario/250_000_secret_values.md
          - 500_000_secret_values: reports/castor/createSecret_scenario/500_000_secret_values.md
          - 750_000_secret_values: reports/castor/createSecret_scenario/750_000_secret_values.md
      - getSecrets:
          - 1_000_secret_values: reports/castor/getSecrets_scenario/1_000_secret_values.md
          - 11_000_secret_values: reports/castor/getSecrets_scenario/11_000_secret_values.md
          - 61_000_secret_values: reports/castor/getSecrets_scenario/61_000_secret_values.md
          - 161_000_secret_values: reports/castor/getSecrets_scenario/161_000_secret_values.md
          - 411_000_secret_values: reports/castor/getSecrets_scenario/411_000_secret_values.md
          - 911_000_secret_values: reports/castor/getSecrets_scenario/911_000_secret_values.md
      - deleteSecret:
          - 1_661_000_secret_values: reports/castor/deleteSecret_scenario/1_661_secret_values.md

  - Ephemeral:
      - emptyProgram:
          - 400000_concurrency_10: reports/ephemeral/getSecrets_scenario/400000_concurrency_10.md
      - scalarValueOptProgram:
          - 400000_concurrency_10: reports/ephemeral/getSecrets_scenario/400000_concurrency_10.md
