name: 'Caliper-Load-Tests'

on:
  push:
  workflow_dispatch:

concurrency:
  group: "Caliper"
  cancel-in-progress: false

jobs:
  caliper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: caliper

      - uses: actions/checkout@v3 # TODO replace with carbynestack/IaC
        with:
          repository: juliangrewe-bosch/carbynestack
          token: ${{secrets.CALIPER_PRIVATE_REPOS_PAT}}
          ref: cdktf-caliper
          path: carbynestack

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - run: npm install --global cdktf-cli@0.16.3

      - name: Provision AzureVM
        id: provision-vm
        run: |
          npm install
          cdktf get
          cdktf synth
          terraform -chdir=cdktf.out/stacks/private-aks/ init -input=false
          terraform -chdir=cdktf.out/stacks/private-aks/ apply -auto-approve -input=false
        working-directory: carbynestack/deployments
        env:
          TF_VAR_adminPassword: ${{ secrets.ADMIN_PASSWORD }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AzureVM IP Address
        id: get-ip
        run: |
          AZURE_VM_IP=$(terraform -chdir=cdktf.out/stacks/private-aks/ output -raw caliper-vm-public-ip)
          echo "AZURE_VM_IP=$AZURE_VM_IP" >> $GITHUB_ENV
          sleep 300 # sleep 5 min until AzureVM provision is done
        working-directory: carbynestack/deployments

      - name: Copy single file to remote
        id: copy-repository
        uses: garygrossgarten/github-action-scp@release
        with:
          local: scripts/run_caliper_load_tests.sh
          remote: home/caliper
          host: ${{ env.AZURE_VM_IP }}
          username: caliper
          password: ${{ secrets.ADMIN_PASSWORD }}
        working-directory: caliper

      - name: Run load-tests
        id: load-tests
        uses: appleboy/ssh-action@v1.0.3
        env:
          CALIPER_PRIVATE_REPOS_PAT: ${{ secrets.CALIPER_PRIVATE_REPOS_PAT }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_T_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          CALIPER_PAT: ${{ secrets.CALIPER_PAT }}
          GITHUB_USERNAME: juliangrewe-bosch
          PRIME: 198766463529478683931867765928436695041
          R: 141515903391459779531506841503331516415
          INVR: 133854242216446749056083838363708373830
          PROGRAM: ephemeral-generic-default
          TUPLE_THRESHOLD: 1000000
        with:
          host: ${{ env.AZURE_VM_IP }}
          username: caliper
          password: ${{ secrets.ADMIN_PASSWORD }}
          command_timeout: 5h
          allenvs: true
          script: |
            # git clone https://github.com/carbynestack/caliper.git
            # git clone https://github.com/carbynestack/carbynestack.git
            env
            printenv
            ls
            ls -l

      - name: Copy single file to remote
        id: copy-repository
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: caliper/caliper
          host: ${{ env.AZURE_VM_IP }}
          username: caliper
          password: ${{ secrets.ADMIN_PASSWORD }}

      - name: Test
        run: |
          ls
          git status
        working-directory: caliper

  destroy:
    needs: caliper
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group delete --name caliper-rg --yes
