name: 'Caliper-load-tests'

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: deployments

jobs:
  Caliper-load-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: juliangrewe-bosch/carbynestack
          ref: cdktf-caliper
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - run: npm install --global cdktf-cli@0.16.3
      - run: az login --service-principal -u ${{secrets.AZURE_SUBSCRIPTION_USERNAME}} -p ${{secrets.AZURE_SUBSCRIPTION_PASSWORD}} --tenant ${{secrets.AZURE_SUBSCRIPTION_TENANT}}
      - name: Provision Azure Virtual Machine
        run: |
          npm install
          cdktf get
          cdktf deploy private-aks --auto-approve true
          cdktf output --outputs-file vm_public_ip.json
        env:
          TF_VAR_adminPassword: ${{secrets.ADMIN_PASSWORD}}
          TF_VAR_isPrivateCluster: true # oder "true"
          # gleiche Authentifizierung wie in der VM ?
      - name: Deploy a Carbynestack Virtual Cloud
        run: |
          # Update package repositories and install necessary tools
          sudo apt-get update
          sudo apt-get install jq -y
          sudo apt-get install sshpass -y

          # SSH into the remote server using sshpass and execute commands
          sshpass -p ${{secrets.ADMIN_PASSWORD}} ssh -o "StrictHostKeyChecking no" caliper@$(cat vm_public_ip.json | jq -r '.["caliper-azure-deployment"]["caliper-vm-public-ip"]') << EOF

          # Set up access to Carbynestacks Github Packages
          echo -e "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" \
                     "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.2.0\"\n" \
                     "          xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" \
                     "          xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.2.0 http://maven.apache.org/xsd/settings-1.2.0.xsd\">\n" \
                     "  <servers>\n" \
                     "    <server>\n" \
                     "      <id>github</id>\n" \
                     "      <username>juliangrewe-bosch</username>\n" \
                     "      <password> ${{secrets.ACCESS_TOKEN}}</password>\n" \
                     "    </server>\n" \
                     "  </servers>\n" \
                     "</settings>" > .m2/settings.xml

          # Configure HashiCorp GPG key and repository
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

          # Configure Kubectl GPG key and repository
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

          # Install NodeSource PPA
          curl -s https://deb.nodesource.com/setup_18.x | sudo bash

          # Update repositories and install required packages
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk nodejs terraform kubectl python3-pip jq

          # Install Azure-CLI
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

          # Install cdktf
          sudo npm install --global cdktf-cli@0.16.3

          # Clone repositories
          git clone https://github.com/juliangrewe-bosch/caliper.git
          git clone https://github.com/juliangrewe-bosch/carbynestack.git

          # Authenticate Terraform to Azure
          az login --service-principal -u ${{secrets.AZURE_SUBSCRIPTION_USERNAME}} -p ${{secrets.AZURE_SUBSCRIPTION_PASSWORD}} --tenant ${{secrets.AZURE_SUBSCRIPTION_TENANT}}

          # Download Prometheus Operator bundle
          LATEST=$(curl -s https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest | jq -cr .tag_name)
          curl -o carbynestack/deployments/manifests/prometheus-operator-bundle.yaml -sL https://github.com/prometheus-operator/prometheus-operator/releases/download/${LATEST}/bundle.yaml

          # Install dependencies and synthesize infrastructure using cdktf
          cd carbynestack/deployments
          npm install
          cdktf get
          cdktf synth

          # Initialize and apply Terraform
          export TF_VAR_azureSubscriptionID=${{secrets.AZURE_SUBSCRIPTION_ID}}
          terraform -chdir=cdktf.out/stacks/private-aks-virtual-cloud/ init -input=false
          terraform -chdir=cdktf.out/stacks/private-aks-virtual-cloud/ apply -auto-approve -input=false

          # Get access credentials for private aks cluster
          az aks get-credentials --name apollo-private --resource-group caliper-rg
          az aks get-credentials --name starbuck-private --resource-group caliper-rg

          # Run load-tests
          cd /home/caliper/caliper
          export STARBUCK_FQDN=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}').sslip.io
          kubectl config use-context apollo-private
          export APOLLO_FQDN=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}').sslip.io
          chmod +x mvnw
          ./mvnw gatling:test

          # Generate report and export to Github Pages
          export APOLLO_NODE_IP=$(kubectl get node -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
          kubectl config use-context starbuck-private
          export STARBUCK_NODE_IP=$(kubectl get node -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')

          python3 scripts/generate_metrics_report.py
          EOF
      - name: Destroy Azure Resources
        run: cdktf destroy --auto-approve true
