name: 'Caliper'

on: [ push ]

defaults:
  run:
    working-directory: terraform
    
jobs:
  Caliper-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install jq
      - uses: appleboy/ssh-action@v1.0.0
        env:
          IP: $(cat vm_public_ip.json | jq -r '.["caliper-azure-deployment"]["caliper-vm-public-ip"]')
          IP2: 1.1.1.1
        with:
          envs: IP, IP2
          host: IP2
          username: caliper
          password: ${{secrets.SSH_PASSWORD}}
          port: 22
          script: |
              echo -e "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" \
                      "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.2.0\"\n" \
                      "          xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" \
                      "          xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.2.0 http://maven.apache.org/xsd/settings-1.2.0.xsd\">\n" \
                      "  <servers>\n" \
                      "    <server>\n" \
                      "      <id>github</id>\n" \
                      "      <username>juliangrewe-bosch</username>\n" \
                      "      <password> ${{secrets.ACCESS_TOKEN}}</password>\n" \
                      "    </server>\n" \
                      "  </servers>\n" \
                      "</settings>" > .m2/settings.xml
              git clone https://github.com/carbynestack/caliper.git /home/caliper/caliper
              cd caliper
              chmod +x mvnw
              ./mvnw compile
      - run: cdktf destroy --auto-approve true
