name: 'Gatling-Tests'

on: [ push ]

jobs:
  bla:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install jq
      - run: echo '{"caliper-azure-deployment":{"caliper-vm-public-ip":"20.238.68.85"}}' > test.json
      - run: ls
      - run: cat test.json | jq -r '.["caliper-azure-deployment"]["caliper-vm-public-ip"]'
  terraform:
    name: "Deploy Azure infrastructure"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - run: npm install --global cdktf-cli@0.16.3
      - run: npm install
        working-directory: terraform
      - run: az login --service-principal -u ${{secrets.AZURE_SUBSCRIPTION_USERNAME}} -p ${{secrets.AZURE_SUBSCRIPTION_PASSWORD}} --tenant ${{secrets.AZURE_SUBSCRIPTION_TENANT}}
      - run: cdktf deploy --auto-approve true
        working-directory: terraform
      - run: ls
        working-directory: terraform
