name: 'Caliper'

on: [ push ]

defaults:
  run:
    working-directory: terraform
    
jobs:
  Caliper-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install jq
      - run: echo '{"caliper-azure-deployment":{"caliper-vm-public-ip":"13.79.234.119"}}' > test.json
      - uses: appleboy/ssh-action@v1.0.0
        env:
          IP: $(cat vm_public_ip.json | jq -r '.["caliper-azure-deployment"]["caliper-vm-public-ip"]')
        with:
          envs: IP
          host: 13.79.234.119
          username: caliper
          password: ${{secrets.SSH_PASSWORD}}
          port: 22
          script: |
              git clone https://github.com/carbynestack/caliper.git /home/caliper/caliper
              cd caliper
              chmod +x mvnw
              ./mvnw compile
      - run: echo "run load-tests"
