name: 'Caliper-load-tests'

on: 
 workflow_dispatch:

defaults:
  run:
    working-directory: terraform

jobs:
  Caliper-load-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install jq
          sudo apt-get install sshpass
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: az
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - run: az
      - run: npm install --global cdktf-cli@0.16.3
      - run: az
      - run: npm install
      - run: az login --service-principal -u ${{secrets.AZURE_SUBSCRIPTION_USERNAME}} -p ${{secrets.AZURE_SUBSCRIPTION_PASSWORD}} --tenant ${{secrets.AZURE_SUBSCRIPTION_TENANT}}
      - run: cdktf deploy --auto-approve true
        env:
          TF_VAR_adminPassword: ${{secrets.ADMIN_PASSWORD}}
      - run: cdktf output --outputs-file vm_public_ip.json
      - run: |
         sshpass -p ${{secrets.ADMIN_PASSWORD}} ssh -o "StrictHostKeyChecking no" caliper@$(cat vm_public_ip.json | jq -r '.["caliper-azure-deployment"]["caliper-vm-public-ip"]') << EOF
         echo -e "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" \
                      "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.2.0\"\n" \
                      "          xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" \
                      "          xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.2.0 http://maven.apache.org/xsd/settings-1.2.0.xsd\">\n" \
                      "  <servers>\n" \
                      "    <server>\n" \
                      "      <id>github</id>\n" \
                      "      <username>juliangrewe-bosch</username>\n" \
                      "      <password> ${{secrets.ACCESS_TOKEN}}</password>\n" \
                      "    </server>\n" \
                      "  </servers>\n" \
                      "</settings>" > .m2/settings.xml
         sudo apt-get install openjdk-8-jdk
         sudo apt-get install nodejs
         sudo apt-get install npm
         az login --service-principal -u ${{secrets.AZURE_SUBSCRIPTION_USERNAME}} -p ${{secrets.AZURE_SUBSCRIPTION_PASSWORD}} --tenant ${{secrets.AZURE_SUBSCRIPTION_TENANT}}
         git clone https://github.com/carbynestack/caliper.git
         cd caliper
         chmod +x mvnw
         ./mvnw compile
         EOF
      - run: cdktf destroy --auto-approve true
