name: Deploy to Github Pages
on:
  push:
#    tags:
#      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install mkdocs-material
          pip install mike==1.1.2

      - name: Configure Git user
        run: |
          git config --local user.email "julian.grewe@de.bosch.com"
          git config --local user.name "juliangrewe-bosch"
      - run: |
          git pull --force
          mike deploy --push test
        working-directory: mkdocs
