name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.TEST }}
          username: caliper
          password: ${{ secrets.ADMIN_PASSWORD }}
          script: |
            export USER=Julian
            ./test.sh
        env:
          TEST: 20.238.44.124
