name: 'Test'

on:
  push:
  workflow_dispatch:

jobs:
  caliper:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Caliper Repository
        id: copy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CALIPER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 137.135.206.217 >> ~/.ssh/known_hosts

          scp caliper@137.135.206.217:/home/caliper/caliper.zip $GITHUB_WORKSPACE
          unzip caliper.zip

      - name: test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 137.135.206.217
          username: caliper
          key: ${{ secrets.CALIPER_PRIVATE_KEY }}
          script: |
#            PATH=$PATH:~/.local/bin
#
#            pip install mkdocs-material
#            pip install mike
#
#            export GIT_COMMITTER_NAME=juliangrewe-bosch
#            export GIT_COMMITTER_EMAIL=julian.grewe@de.bosch.com
#
#            cd "$HOME"/caliper/mkdocs || exit 1
#
#            git fetch origin
#            git branch gh-pages origin/gh-pages
#
#            export DATE=$(date +"%d-%m-%Y")
#            mike deploy "$DATE" latest --push --update-aliases
