name: 'Test'

on:
  push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy a Carbynestack Virtual Cloud
        run: |
          # Update package repositories and install necessary tools
          sudo apt-get update
          sudo apt-get install sshpass -y

          # SSH into the remote server using sshpass and execute commands
          sshpass -p ${{secrets.ADMIN_PASSWORD}} ssh -o "StrictHostKeyChecking no" caliper@68.219.95.118 << EOF

          export STARBUCK_FQDN=\$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}').sslip.io
          kubectl config use-context apollo-private
          export APOLLO_FQDN=\$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}').sslip.io
          cd caliper
          chmod +x mvnw
          ./mvnw gatling:test
          EOF

       
