name: 'Test'

on:
  push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy a Carbynestack Virtual Cloud
        run: |
          # Update package repositories and install necessary tools
          sudo apt-get update
          sudo apt-get install sshpass -y

          # SSH into the remote server using sshpass and execute commands
          sshpass -p ${{secrets.ADMIN_PASSWORD}} ssh -o "StrictHostKeyChecking no" caliper@68.219.95.118 << EOF
          
          LATEST=\$(curl -s https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest | jq -cr .tag_name)
          curl -o carbynestack/deployments/manifests/prometheus-operator-bundle.yaml -sL https://github.com/prometheus-operator/prometheus-operator/releases/download/\${LATEST}/bundle.yaml
          EOF

       
