name: 'Test'

on:
  push

defaults:
  run:
    working-directory: carbynestack/deployments

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: juliangrewe-bosch/carbynestack
          token: ${{secrets.CALIPER_PRIVATE_REPOS_PAT}}
          path: carbynestack
          ref: cdktf-caliper
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - run: npm install --global cdktf-cli@0.16.3
      - name: Deploy a Carbynestack Virtual Cloud
        run: |
          # Update package repositories and install necessary tools
          sudo apt-get update
          sudo apt-get install sshpass -y

          # SSH into the remote server using sshpass and execute commands
          sshpass -p ${{secrets.ADMIN_PASSWORD}} ssh -o "StrictHostKeyChecking no" caliper@68.219.100.76 << EOF

          latest_tag=$(curl -s https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest | jq -r .tag_name)
          url="https://github.com/prometheus-operator/prometheus-operator/releases/download/$latest_tag/bundle.yaml"
          curl -sL $url > bundle.yaml
