name: 'Test'

on:
  push:
  workflow_dispatch:

jobs:
  caliper:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 20.166.86.218
          username: caliper
          key: ${{ secrets.CALIPER_PRIVATE_KEY }}
          script: |
            env
            export PATH="$HOME"/.local/bin

            pip install mkdocs-material
            pip install mike

            export GITHUB_USER=juliangrewe-bosch
            export GITHUB_USER_MAIL=julian.grewe@de.bosch.com

            cd "$HOME"/caliper/mkdocs || exit 1

            git config --local user.email "$GITHUB_USER_MAIL"
            git config --local user.name "$GITHUB_USER"

            git fetch origin
            git branch gh-pages origin/gh-pages

            export DATE=$(date +"%d-%m-%Y")
            mike deploy "$DATE" latest --push --update-aliases
