name: 'Test'

on:
  push:
  workflow_dispatch:

jobs:
  caliper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: caliper
      - name: Copy MkDocs Directory
        id: copy-mkdocs
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CALIPER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 137.135.206.217 >> ~/.ssh/known_hosts

          scp caliper@137.135.206.217:/home/caliper/caliper/mkdocs/docs/images/charts.zip .
          unzip charts.zip
          cp -r charts/ $GITHUB_WORKSPACE/caliper/mkdocs/docs/images/

      - name: Deploy latest Report
        id: deploy-report
        run: |
          pip install mkdocs-material
          pip install mike

          cd $GITHUB_WORKSPACE/caliper/mkdocs || exit 1

          git config user.name juliangrewe-bosch
          git config user.email julian.grewe@de.bosch.com

          git fetch origin
          git branch gh-pages origin/gh-pages

          export DATE=$(date +"%d-%m-%Y")
          mike deploy "$DATE" latest --update-aliases
