name: 'Test'

on:
  #push:
  workflow_dispatch:

jobs:
  caliper:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 20.223.130.224
          username: caliper
          key: ${{ secrets.CALIPER_PRIVATE_KEY }}
          script: |
            export CALIPER_PRIVATE_REPOS_PAT=${{ secrets.CALIPER_PRIVATE_REPOS_PAT }}
            export AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
            export AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
            export AZURE_T_ID=${{ secrets.AZURE_TENANT_ID }}
            export AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
            export CALIPER_PAT=${{ secrets.CALIPER_PAT }}
            export GITHUB_USERNAME=juliangrewe-bosch
            export PRIME=198766463529478683931867765928436695041
            export R=141515903391459779531506841503331516415
            export INVR=133854242216446749056083838363708373830
            export PROGRAM=ephemeral-generic-default
            export TUPLE_THRESHOLD=1000000 # klyshko config

            git clone https://github.com/juliangrewe-bosch/caliper.git "$HOME/caliper"
            git -C "$HOME/caliper" checkout -b caliper-workflow origin/caliper-workflow

            "$HOME/run_caliper_load_tests.sh"
            chmod +x "$HOME/caliper/scripts/run_caliper_load_tests.sh"
            mv "$HOME/caliper/scripts/run_caliper_load_tests.sh" "$HOME"
            "$HOME/run_caliper_load_tests.sh"
