name: 'Test'

on:
  #push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  caliper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: caliper
      - name: Run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 137.116.241.211
          username: caliper
          key: ${{ secrets.CALIPER_PRIVATE_KEY }}
          command_timeout: 5h
          script: |
            cd "$HOME"/caliper
            ./mvnw gatling:test
