name: Example Workflow
on:
  repository_dispatch:
    types: [update_report]
jobs:
  update-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: message
          file_pattern: mkdocs/*
          tagging_message: 'v2024-01-12'

  deploy:
    needs: update-report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install mkdocs-material
          pip install mike
      - run: |
          mike deploy ${GITHUB_REF#refs/tags/} latest -p
        working-directory: mkdocs
