site_name: Caliper
#site_url: https://caliper.io/
site_author: Carbyne Stack Community
site_description: >-
  Caliper Load-Tests Report
  copyright: "Copyright © 2021-2023 The Carbyne Stack Authors"

repo_url: https://github.com/juliangrewe-bosch/caliper
repo_name: caliper
#edit_uri: https://github.com/carbynestack/carbynestack.github.io/edit/master/docs  ?

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home: index.md
  - Amphora:
      - ScenarioX:
          - Gatling: reports/amphora/scenarioX/gatling.md
          - cAdvisor: reports/amphora/scenarioX/cAdvisor.md
  - Castor:
      - ScenarioX:
          - cAdvisor: reports/castor/scenarioX/cAdvisor.md
  - Ephemeral:
      - ScenarioX:
          - Gatling: reports/ephemeral/scenarioX/gatling.md
          - cAdvisor: reports/ephemeral/scenarioX/cAdvisor.md
